import { useEffect, useRef, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Navigate, NavLink, Route, Routes, useLocation } from "react-router-dom";
import type { Result } from "../../mcp-app/src/schema";
import { api, passkey, useResource } from "./api";
import { Button } from "./components/ui/button";
import { SchemaForm, type Schema, type Value } from "./schema-form";
import "./style.css";
import snapshot from "../../../hirz/adapters/doorbell/twin/snapshot.svg?inline";

type Session = { authenticated: boolean; member?: { member_id: string; display_name: string; role: string } };
type Plan = NonNullable<Result["data"]["plan"]>;
type Review = { recorded?: boolean; id: string; candidate_hash: string; sentence: string; candidate: string; review: { lines: string[]; yaml_diff: string; cedar: string; analysis: string } };
type Constitution = { recorded_demo: boolean; yaml: string; document: Value; schema: Schema; version: number; status: string; history: { version: number; status: string; yaml: string }[]; drafting: string; proposals: { id: string; text: string; author: string | null; surface: string; status: string; failure: string | null; draft_id: string | null }[]; drafts: (Review & { status: string })[] };
type Action = { action_id: string; class: string; reason: string; content_hash: string; params: Record<string, Value>; plan_id: string | null; target: { adapter: string; entity: string } };
type Pending = { risk_band: string; id: string; status: string; expires_at: string; quorum: string; action: Action };
const requestId = () => crypto.randomUUID();
const date = (value: string) => new Date(value).toLocaleString();

function AsyncButton({ children, run, primary = false, disabled = false }: { children: ReactNode; run: () => Promise<unknown>; primary?: boolean; disabled?: boolean }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  return <div><Button variant={primary ? "default" : "outline"} disabled={busy || disabled} onClick={async () => {
    setBusy(true); setMessage("");
    try { await run(); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed."); }
    finally { setBusy(false); }
  }}>{busy ? "Please wait…" : children}</Button>{message && <p role="alert">{message}</p>}</div>;
}
function Load({ error, retry }: { error: string; retry: () => void }) {
  return error ? <div role="alert"><p>{error}</p><Button onClick={retry}>Retry</Button></div> : <p role="status">Loading…</p>;
}
function Panel({ title, children, id }: { title: string; children: ReactNode; id?: string }) { return <section id={id} tabIndex={id ? -1 : undefined} className="panel"><h2>{title}</h2>{children}</section>; }
function Secret({ value }: { value: string }) { return <div role="status" className="secret"><h2>Save this code now</h2><p>Keep it somewhere private. It is shown once and only permits enrolling a replacement passkey.</p><code>{value}</code></div>; }

function Login({ refresh }: { refresh: () => void }) {
  const [token, setToken] = useState(""), [secret, setSecret] = useState("");
  return <main className="login"><p className="wordmark">Hirz</p><h1>Your household, your rules.</h1><p>Sign in with your own passkey to review rules and respond to requests.</p>{secret ? <><Secret value={secret} /><Button variant="default" onClick={refresh}>I saved my recovery code</Button></> : <>
    <AsyncButton primary run={async () => { await passkey({ operation: "login" }); refresh(); }}>Sign in with a passkey</AsyncButton>
    <details><summary>Set up a passkey or recover access</summary><label>Invitation or one-time recovery code<input autoComplete="off" type="password" value={token} onChange={e => setToken(e.target.value)} /></label><AsyncButton disabled={!token} run={async () => { const result = await passkey({ operation: "enroll", token }); setToken(""); if (result.recovery_code) setSecret(result.recovery_code); else refresh(); }}>Enroll a passkey</AsyncButton></details>
    <p className="muted">Owners need a remaining passkey or recovery code to recover access. Local setup cannot reset an enrolled member.</p></>}</main>;
}
function Tonight() {
  const r = useResource<{ plan: Plan | null; preparation: string | null; devices: { name: string; kind: string }[]; policy_status: string; paused: boolean }>("/tonight", true);
  const [message, setMessage] = useState(""), [limit, setLimit] = useState(50), [device, setDevice] = useState("");
  if (!r.data || r.error) return <Load {...r} />;
  const { plan, paused, policy_status } = r.data;
  const tool = async (name: string, input: object) => { const result = await api<Result>(`/tools/${name}`, { ...input, request_id: requestId() }); setMessage(result.speakable.headline); r.retry(); };
  return <><p className="eyebrow">YOUR HOUSEHOLD</p><h1>Tonight</h1>{policy_status !== "active" ? <Panel title="Activate your household rules"><p>Review and activate the initial policy before starting automation.</p><NavLink to="/constitution">Review household rules →</NavLink></Panel> : <>
    <Panel title={paused ? "Automation is paused" : "Household automation"}><p>{paused ? "Already-authorized bounded endings still finish." : "Hirz follows your active household rules."}</p><AsyncButton run={async () => { if (paused) await api("/resume", {}); else await tool("execute_household_action", { action: "pause_automation" }); r.retry(); }}>{paused ? "Resume automation" : "Pause automation"}</AsyncButton></Panel>
    <Panel title={plan ? "Your current plan" : "Prepare tonight’s plan"}>{plan ? <><p className="badge">{plan.status}</p><p>{date(plan.horizon.start)} – {date(plan.horizon.end)}</p>{plan.comparison_validity.valid && plan.summary.estimated_savings_usd !== null && <p className="figure">{new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(plan.summary.estimated_savings_usd)}<span> estimated saving</span></p>}{plan.alternatives.map((a, i) => <p key={i}>{a.label}: {a.why_rejected}</p>)}<AsyncButton primary disabled={paused || ["refreshing", "blocked", "approved", "executing"].includes(plan.status)} run={() => tool("approve_action", { plan_id: plan.plan_id, version: plan.version, approved: true })}>Approve this plan</AsyncButton><AsyncButton run={() => tool("approve_action", { plan_id: plan.plan_id, version: plan.version, approved: false })}>Skip this plan</AsyncButton></> : <><p role="status">{r.data.preparation === "pending" ? "The worker is preparing your plan…" : r.data.preparation === "failed" ? "Planning is blocked: the configured inputs did not produce an available plan." : "The worker prepares the plan from the household’s configured inputs."}</p><AsyncButton primary disabled={r.data.preparation === "pending"} run={() => tool("get_household_plan", { horizon: "tonight" })}>{r.data.preparation === "failed" ? "Retry plan preparation" : "Prepare plan"}</AsyncButton></>}</Panel>{plan && <Panel title="Change tonight’s plan"><AsyncButton run={() => tool("explain_plan", { plan_id: plan.plan_id, focus: "summary" })}>Why this plan?</AsyncButton><label>Car<select value={device} onChange={e => setDevice(e.target.value)}><option value="">Choose a car</option>{r.data.devices.filter(d => d.kind === "ev").map(d => <option key={d.name}>{d.name}</option>)}</select></label><label>Maximum charge (%)<input type="number" min={0} max={80} value={limit} onChange={e => setLimit(Number(e.target.value))} /></label><AsyncButton disabled={!device || limit < 0 || limit > 80} run={() => tool("revise_household_plan", { text: `Keep ${device} at or below ${limit}% tonight`, applies_to: device, kind: "constraint", operation: "add", change: "car_limit", percent: limit })}>Update charge limit</AsyncButton><p className="muted">Review the refreshed plan before approving it.</p></Panel>}</>}{message && <p role="status">{message}</p>}</>;
}
function RuleReview({ draft, done }: { draft: Review; done: () => void }) {
  const [complete, setComplete] = useState(false);
  const panel = useRef<HTMLElement>(null);
  useEffect(() => { panel.current?.scrollIntoView({ block: "start" }); panel.current?.focus({ preventScroll: true }); }, [draft.id]);
  return <section ref={panel} tabIndex={-1} aria-label="Rule review" className="panel phone-screen"><p className="eyebrow">REVIEW YOUR RULE</p><h2>{draft.sentence || "Review your household rules"}</h2>{draft.recorded && <p className="badge">Recorded demo patch · no model call</p>}<ul className="situations">{draft.review.lines.slice(0, 3).map((line, i) => <li key={i}>{line}</li>)}</ul>{!draft.review.lines.length && <p>No sampled situation changes.</p>}{!draft.review.lines.some(line => line.includes("does not identify")) && <p>Hirz does not identify the visitor.</p>}<details onToggle={e => { if (e.currentTarget.open) void api("/constitution/review", { id: draft.id }).then(() => setComplete(true)).catch(() => setComplete(false)); }}><summary>Complete review ({draft.review.lines.length} lines) and YAML changes</summary><ul>{draft.review.lines.map((line, i) => <li key={i}>{line}</li>)}</ul><pre>{draft.review.yaml_diff}</pre></details><details><summary>Compiled Cedar</summary><pre>{draft.review.cedar}</pre></details><p className="muted">dogwood-local · {draft.review.analysis}</p><AsyncButton primary disabled={draft.review.lines.length > 3 && !complete} run={async () => { await passkey({ operation: "activate", draft_id: draft.id, candidate_hash: draft.candidate_hash }); done(); }}>Activate with passkey</AsyncButton></section>;
}
function ConstitutionPage() {
  const r = useResource<Constitution>("/constitution", true);
  const [yaml, setYaml] = useState<string>(), [form, setForm] = useState<Value>(), [mode, setMode] = useState("yaml"), [review, setReview] = useState<Review>(), [sentence, setSentence] = useState(""), [proposal, setProposal] = useState<string>();
  if (!r.data || r.error) return <Load {...r} />;
  const data = r.data;
  return <><p className="eyebrow">HOUSE RULES</p><h1>Constitution</h1><p>Version {data.version} · {data.status} · dogwood-local</p><p className="muted">not analyzed: local mode</p>{review && <RuleReview key={review.id} draft={review} done={() => { setReview(undefined); setYaml(undefined); setForm(undefined); setProposal(undefined); r.retry(); }} />}
    <Panel title="Edit the rules"><div className="flex gap-2"><Button aria-pressed={mode === "yaml"} onClick={() => setMode("yaml")}>YAML</Button><AsyncButton run={async () => { setForm(await api<Value>("/constitution/parse", { yaml: yaml ?? data.yaml })); setMode("form"); }}>Form</AsyncButton></div>{mode === "yaml" ? <label>Household policy YAML<textarea rows={18} spellCheck={false} value={yaml ?? data.yaml} onChange={e => setYaml(e.target.value)} /></label> : <SchemaForm schema={data.schema} value={form ?? data.document} onChange={value => { setForm(value); setYaml(JSON.stringify(value, null, 2)); }} />}<label>Describe your change<input value={sentence} onChange={e => setSentence(e.target.value)} /></label><AsyncButton run={async () => setReview(await api<Review>("/constitution/draft", { yaml: yaml ?? data.yaml, sentence, proposal_id: proposal }))}>Preview changes</AsyncButton>{<AsyncButton disabled={!sentence} run={async () => { await api("/tools/propose_household_rule", { text: sentence, request_id: requestId() }); r.retry(); }}>Propose this rule</AsyncButton>}{data.recorded_demo && <><p className="muted">Recorded demo supports: Never unlock for an unexpected visitor</p><AsyncButton disabled={!sentence} run={async () => setReview(await api<Review>("/constitution/recorded-draft", { sentence, proposal_id: proposal }))}>Preview recorded English patch</AsyncButton></>}</Panel>
    <Panel title="Proposed rules"><p>Voice proposals are suggestions. Only an owner’s passkey activation changes the rules.</p>{data.proposals.length ? data.proposals.map(p => <article key={p.id}><p>{p.text}</p><p className="muted">From {p.author ?? "a former linked member"} via {p.surface} · {p.status}</p>{p.failure && <p>{p.failure}</p>}{!["activated", "dismissed"].includes(p.status) && <><Button onClick={() => { setSentence(p.text); setProposal(p.id); }}>Use this sentence while editing</Button>{p.draft_id && <Button onClick={() => setReview(data.drafts.find(d => d.id === p.draft_id))}>Review drafted changes</Button>}<AsyncButton run={async () => { await api("/constitution/dismiss", { id: p.id }); r.retry(); }}>Dismiss proposal</AsyncButton></>}</article>) : <p>No proposals yet.</p>}<p className="muted">{data.drafting === "off" ? "English drafting is disabled. Voice proposals stay queued for manual editing." : "English proposals are queued for drafting. Review every change before activation."}</p></Panel>
    {data.drafts.filter(d => d.status === "ready").length > 0 && <Panel title="Saved reviews">{data.drafts.filter(d => d.status === "ready").map(d => <Button key={d.id} onClick={() => setReview(d)}>{d.sentence || "Review saved changes"}</Button>)}</Panel>}
    <Panel title="Policy history">{data.history.map(h => <article key={h.version}><h3>Version {h.version} · {h.status}</h3><AsyncButton disabled={h.status === "active"} run={async () => setReview(await api<Review>("/constitution/draft", { yaml: h.yaml, sentence: `Restore version ${h.version}` }))}>Review rollback</AsyncButton></article>)}</Panel></>;
}
function PushSetup() {
  const state = useResource<{ available: boolean; public_key: string | null; deliveries: { status: string; attempts: number }[] }>("/push", true);
  const [message, setMessage] = useState("");
  return <Panel title="Phone notifications"><p>On iPhone, add Hirz to your Home Screen, then open it there to enable notifications.</p><AsyncButton disabled={!state.data?.available} run={async () => {
    if (!("Notification" in window) || !("serviceWorker" in navigator)) throw new Error("Push is unavailable in this browser. iPhone notifications require iOS 16.4 or later and the Home Screen app. Your approval inbox remains usable.");
    const permission = await Notification.requestPermission();
    if (permission !== "granted") throw new Error("Notifications were not enabled. Use your approval inbox.");
    const worker = await navigator.serviceWorker.register("/sw.js");
    await navigator.serviceWorker.ready;
    const key = Uint8Array.from(atob(state.data!.public_key!.replace(/-/g, "+").replace(/_/g, "/")), c => c.charCodeAt(0));
    const subscription = await worker.pushManager.getSubscription() ?? await worker.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: key });
    await api("/push/subscribe", subscription.toJSON()); setMessage("Notifications enabled on this browser."); state.retry();
  }}>Enable notifications</AsyncButton>{state.data && !state.data.available && <p>Push is not configured. Requests remain in your approval inbox.</p>}{message && <p role="status">{message}</p>}{state.data?.deliveries.map((d, i) => <p key={i}>{d.status} · {d.attempts} delivery attempts</p>)}</Panel>;
}
function Approvals() {
  const [message, setMessage] = useState(""), [requestedApproval, setRequestedApproval] = useState<string>();
  const r = useResource<{ approvals: Pending[]; locks: { name: string; observation: { source: string; observed_at: string; state: { locked: boolean | null; available: boolean | null } } | null }[]; demo_controls: boolean; door: { context: string[]; snapshot: string | null; lock_state: string } | null }>("/approvals", true);
  useEffect(() => {
    if (!requestedApproval || !r.data?.approvals.some(p => p.id === requestedApproval)) return;
    const card = document.getElementById(`approval-${requestedApproval}`);
    card?.scrollIntoView({ block: "start" });
    card?.focus({ preventScroll: true });
    setRequestedApproval(undefined);
  }, [requestedApproval, r.data]);
  if (!r.data || r.error) return <Load {...r} />;
  return <><p className="eyebrow">YOUR DECISION</p><h1>Approvals</h1><PushSetup />{r.data.demo_controls && <Panel title="Disposable phone test"><p className="badge">simulated</p><AsyncButton run={async () => { await api("/twin/doorbell", {}); const result = await api<Result>("/tools/execute_household_action", { action: "request_door_unlock", minutes: 1, request_id: requestId() }); const approval = result.data.decision?.approval; setRequestedApproval(approval?.approval_id); setMessage(approval ? "Request ready. Review the unlock approval below, then choose Approve with passkey." : result.speakable.headline); r.retry(); }}>Ring twin doorbell and request a one-minute unlock</AsyncButton>{message && <p role="status">{message}</p>}</Panel>}{(r.data.locks ?? []).map(lock => <Panel key={lock.name} title="Door read-back"><p>{lock.name}</p><p className="badge">{lock.observation?.source === "real" ? "live" : "simulated"}</p><p role="status">{lock.observation?.state.available === true && typeof lock.observation.state.locked === "boolean" ? lock.observation.state.locked ? "locked" : "unlocked" : "unavailable; actual state unknown"}</p>{lock.observation && <p className="muted">Observed {date(lock.observation.observed_at)}</p>}</Panel>)}{!r.data.approvals.length && <Panel title="You’re all caught up"><p>No eligible pending requests.</p></Panel>}{r.data.approvals.map(p => <Panel key={p.id} id={`approval-${p.id}`} title={p.action.class.startsWith("security.") ? "Unlock approval" : "A household action needs you"}><p className="badge">{p.action.target.adapter === "twin" ? "simulated" : "Device request"}</p><p>{p.action.reason}</p><p>{p.status} · {p.quorum.replaceAll("_", " ")} · Expires {date(p.expires_at)}</p>{p.action.class.startsWith("security.") ? <div className="phone-screen">{r.data?.door?.snapshot === "twin" && <img src={snapshot} alt="Simulated doorbell snapshot" />}<h2>Someone is at the front door.</h2>{r.data?.door?.context.map((line, i) => <p key={i}>{line}</p>)}<p>Unlock for {String(p.action.params.open_minutes)} {Number(p.action.params.open_minutes) === 1 ? "minute" : "minutes"}?</p><p className="muted">Household security rule · {p.risk_band} risk</p><p>I confirm this request. A schedule does not identify the visitor.</p><div className="flex gap-2">{[true, false].map(approved => <AsyncButton primary={approved} key={String(approved)} run={async () => { await passkey({ operation: "approve", approval_id: p.id, action_hash: p.action.content_hash, approved }); r.retry(); }}>{approved ? "Approve with passkey" : "Deny"}</AsyncButton>)}</div></div> : <div className="flex gap-2">{[true, false].map(approved => <AsyncButton primary={approved} key={String(approved)} run={async () => { await api("/tools/approve_action", { action_id: p.action.action_id, approval_id: p.id, approved, request_id: requestId() }); r.retry(); }}>{approved ? "Approve" : "Deny"}</AsyncButton>)}</div>}</Panel>)}</>;
}
function Household() {
  const r = useResource<{ graph: Record<string, Record<string, Value>[]>; credentials: { credential_id: string; label: string; revoked_at: string | null; member_id: string }[] }>("/household");
  const [secret, setSecret] = useState(""), [lockout, setLockout] = useState(false);
  if (!r.data || r.error) return <Load {...r} />;
  return <><h1>Household</h1>{secret && <Secret value={secret} />}<Panel title="Passkeys"><p>Add a second distinct credential, especially for the owner. Passkeys may sync across devices.</p><AsyncButton run={async () => { await passkey({ operation: "add_credential" }); r.retry(); }}>Add a passkey</AsyncButton><label><input type="checkbox" checked={lockout} onChange={e => setLockout(e.target.checked)} /> I understand revoking the last passkey may lock this member out.</label>{r.data.credentials.map(k => <article key={k.credential_id}><h3>{k.label}</h3>{k.revoked_at ? <p>Revoked {date(k.revoked_at)}</p> : <AsyncButton run={async () => { await passkey({ operation: "revoke", credential_id: k.credential_id, confirm_lockout: lockout }); r.retry(); }}>Revoke passkey</AsyncButton>}</article>)}</Panel><Panel title="Members">{r.data.graph.members.map(m => <article key={String(m.id)}><h3>{String(m.display_name)}</h3><p>{String(m.role)}</p>{m.role !== "owner" && <AsyncButton run={async () => { const result = await passkey({ operation: "reinvite", member_id: m.id }); setSecret(result.invitation ?? ""); }}>Issue a new invitation</AsyncButton>}</article>)}</Panel><Panel title="Devices">{r.data.graph.assets.map(a => <article key={String(a.id)}><h3>{String(a.name)}</h3><p>{a.managed_through_hirz === true ? "Managed through Hirz" : "Not managed"}</p></article>)}</Panel><Panel title="Schedules">{(r.data.graph.schedules ?? []).map(row => <p key={String(row.id)}>{String(row.name)}</p>)}</Panel><Panel title="Trusted contacts">{(r.data.graph.trusted_contacts ?? []).map(row => <article key={String(row.id)}><h3>{String(row.display_name ?? row.name)}</h3><AsyncButton run={async () => { await api("/contacts/remove", { id: row.id }); r.retry(); }}>Remove contact and close pending checks</AsyncButton></article>)}</Panel></>;
}
function Audit() {
  const [event, setEvent] = useState(""), [before, setBefore] = useState<number>();
  const r = useResource<{ rows: { seq: number; event_type: string; created_at: string; payload: Value; curr_hash: string }[]; anchoring: string }>(`/audit?event=${encodeURIComponent(event)}${before === undefined ? "" : `&before=${before}`}`);
  return <><h1>Audit</h1><p>The household’s signed record.</p><label>Filter by event<select value={event} onChange={e => { setEvent(e.target.value); setBefore(undefined); }}>{["", "CONSTITUTION_ACTIVATED", "APPROVED", "EXECUTED", "VERIFIED", "DENY_CONSTITUTION"].map(v => <option key={v} value={v}>{v || "All events"}</option>)}</select></label><Button asChild><a href="/api/audit/export">Verify and download signed export</a></Button>{!r.data || r.error ? <Load {...r} /> : <><p className="muted">{r.data.anchoring}</p>{r.data.rows.map(row => <details className="panel" key={row.seq}><summary>{row.event_type.replaceAll("_", " ")} · {date(row.created_at)}</summary><p>Sequence {row.seq}</p><pre>{JSON.stringify(row.payload, null, 2)}</pre><p className="hash">{row.curr_hash}</p></details>)}<div className="flex gap-2">{before !== undefined && <Button onClick={() => setBefore(undefined)}>Latest events</Button>}{r.data.rows.length === 100 && <Button onClick={() => setBefore(r.data!.rows.at(-1)!.seq)}>Older events</Button>}</div></>}</>;
}
type TwinRun = { id: string; scenario: string; at: string; refreshing: boolean; controls: { paused: boolean; speed: number }; snapshot: { status: string; error?: string; claim?: string; checkins: { contact: string; requested_at: string; reply_at: string; deadline: string; status: string }[]; observations?: Value[]; limitations?: string[] } | null };
function Twin() {
  const r = useResource<{ scenarios: { id: string; start: string; end: string }[]; runs: TwinRun[] }>("/twin", true);
  const [scenario, setScenario] = useState("parents-scam-check"), [event, setEvent] = useState('{"at":"17:01","event":"doorbell.press","entity":"doorbell.front_door"}');
  if (!r.data || r.error) return <Load {...r} />;
  const run = r.data.runs[0];
  const control = async (operation: string, extra: object = {}) => { await api("/twin/control", { operation, ...(operation === "start" ? { scenario } : { id: run?.id }), ...extra }); r.retry(); };
  return <><p className="eyebrow">SIMULATED HOUSEHOLD</p><h1>Twin</h1><p>Isolated repository scenarios. Scripted approvals and replies are simulations and never authenticate an action.</p><Panel title="Start an isolated run"><label>Repository scenario<select value={scenario} onChange={e => setScenario(e.target.value)}>{r.data.scenarios.map(s => <option key={s.id}>{s.id}</option>)}</select></label><AsyncButton run={() => control("start")}>Start scenario</AsyncButton></Panel>{run && <><Panel title={run.scenario}><p className="badge">simulated</p><p>{date(run.at)} · {run.controls.paused ? "Paused" : `${run.controls.speed}× clock`}</p><p role="status">{run.refreshing ? "Refreshing scenario snapshot…" : run.snapshot?.status}</p><div className="flex gap-2"><AsyncButton run={() => control(run.controls.paused ? "resume" : "pause")}>{run.controls.paused ? "Resume at 60×" : "Pause clock"}</AsyncButton><AsyncButton run={() => control("step", { minutes: 1 })}>Step one minute</AsyncButton></div>{run.snapshot?.error && <p role="alert">{run.snapshot.error}</p>}<p>Snapshots include events before the displayed time. Replay may take a moment.</p></Panel>{run.snapshot?.checkins.map(check => <section key={check.contact} className="panel phone-screen"><p className="badge">SIMULATED CHECK-IN</p><h2>Your mom is checking it’s really you.</h2><p>Did you make this request?</p>{run.snapshot?.claim && <blockquote>{run.snapshot.claim}</blockquote>}<p>{check.status.replaceAll("_", " ")}</p><div className="grid gap-2">{[["not_genuine", "No, that wasn’t me"], ["genuine", "Yes, that was me"], ["will_call", "I’ll call her"]].map(([reply, label]) => <AsyncButton key={reply} primary={reply === "not_genuine"} disabled={check.status !== "pending" || run.refreshing} run={() => control("inject", { event: { at: check.reply_at, event: "contact.checkin_reply", contact: check.contact, reply, requested_at: check.requested_at, deadline: check.deadline } })}>{label}</AsyncButton>)}</div><p className="muted">This changes only the isolated scenario. No real message or call is sent.</p></section>)}<Panel title="Inject a supported event"><label>Typed scenario event JSON<textarea value={event} onChange={e => setEvent(e.target.value)} rows={5} /></label><p>Presence, recovery, doorbell, inbound-call and simulated check-in events use the repository scenario schema.</p><AsyncButton run={() => control("inject", { event: JSON.parse(event) })}>Inject simulated event</AsyncButton></Panel><details className="panel"><summary>Source-labeled observations and limitations</summary>{run.snapshot?.limitations?.map(line => <p key={line}>{line}</p>)}<pre>{JSON.stringify(run.snapshot?.observations ?? [], null, 2)}</pre></details></>}</>;
}
function Shell({ session, refresh }: { session: Session; refresh: () => void }) {
  const location = useLocation();
  return <div className="shell"><a className="skip" href="#main">Skip to content</a><aside><NavLink to="/tonight" className="wordmark">Hirz</NavLink><p className="muted">{session.member?.display_name}’s household</p><nav aria-label="Main">{["tonight", "approvals", "constitution", "household", "audit", "twin"].map(page => <NavLink key={page} to={`/${page}`}>{page[0].toUpperCase() + page.slice(1)}</NavLink>)}</nav><AsyncButton run={async () => { await api("/auth/logout", {}); refresh(); }}>Sign out</AsyncButton></aside><main id="main" tabIndex={-1} key={location.pathname}><Routes><Route path="/tonight" element={<Tonight />} /><Route path="/constitution" element={<ConstitutionPage />} /><Route path="/approvals" element={<Approvals />} /><Route path="/household" element={<Household />} /><Route path="/audit" element={<Audit />} /><Route path="/twin" element={<Twin />} /><Route path="*" element={<Navigate replace to="/tonight" />} /></Routes></main></div>;
}
function App() {
  const session = useResource<Session>("/auth/session");
  if (!session.data || session.error) return <main className="login"><Load {...session} /></main>;
  return session.data.authenticated ? <Shell session={session.data} refresh={session.retry} /> : <Login refresh={session.retry} />;
}
createRoot(document.getElementById("root")!).render(<BrowserRouter><App /></BrowserRouter>);
