import { test, expect, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

// Results are generated by the authenticated disposable twin smoke, never hand-entered figures.
const fixtures = JSON.parse(readFileSync(process.env.HIRZ_CARD_FIXTURES!, "utf8"));
const tools: Record<string, string> = { plan: "get_household_plan", approval: "execute_household_action", verification: "assess_request_risk", doorbell: "get_household_context", scorecard: "get_action_audit" };
type Request = { name: string; arguments: Record<string, unknown> };

// Freeze Date while leaving the unchanged host SDK's transport timers running.
async function advance(page: Page, milliseconds: number) {
  const at = await page.evaluate(() => Date.now());
  await page.clock.setFixedTime(new Date(at + milliseconds));
  await page.waitForTimeout(milliseconds);
}

async function mount(page: Page, kind: string, theme = "light", respond?: (request: Request) => unknown, initial = fixtures.results[kind]) {
  await page.emulateMedia({ colorScheme: theme as "light" | "dark" });
  await page.clock.setFixedTime(new Date(fixtures.at));
  const calls: Request[] = [];
  await page.route("http://127.0.0.1:8082/mcp", async route => {
    if (route.request().method() === "GET") return route.fulfill({ status: 405 });
    const request = route.request().postDataJSON();
    let result: unknown;
    if (request.method === "initialize") result = { protocolVersion: "2025-11-25", capabilities: { tools: {}, resources: {} }, serverInfo: { name: "Labeled twin fixtures", version: "1" } };
    if (request.method === "tools/list") result = { tools: fixtures.tools };
    if (request.method === "resources/list") result = { resources: [] };
    if (request.method === "resources/read") {
      const name = request.params.uri.replace("ui://hirz/", "");
      result = { contents: [{ uri: request.params.uri, mimeType: "text/html;profile=mcp-app", text: readFileSync(resolve("../../hirz/mcp/ui", name + ".html"), "utf8"), _meta: { ui: { csp: { connectDomains: [], resourceDomains: [] } } } }] };
    }
    if (request.method === "tools/call") {
      calls.push(request.params);
      const value = calls.length > 1 && respond ? await respond(request.params) : initial;
      result = value instanceof Error ? { isError: true, content: [{ type: "text", text: value.message }] } : { content: [{ type: "text", text: JSON.stringify(value) }], structuredContent: value };
    }
    if (request.id === undefined) return route.fulfill({ status: 202, body: "" });
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ jsonrpc: "2.0", id: request.id, result }) });
  });
  await page.goto(`http://localhost:8080/?tool=${tools[kind]}`);
  await expect(page.getByRole("combobox", { name: "Tool", exact: true })).toHaveValue(tools[kind]);
  const properties = fixtures.tools.find((tool: { name: string }) => tool.name === tools[kind]).inputSchema.properties;
  const defaultField = Object.entries<{ default?: unknown }>(properties).find(entry => Object.hasOwn(entry[1], "default"))?.[0];
  await expect(page.getByRole("textbox", { name: "Input" })).toHaveValue(defaultField ? new RegExp(defaultField) : "{}");
  await page.getByRole("textbox", { name: "Input" }).fill(JSON.stringify(fixtures.inputs?.[kind] ?? {}));
  await page.getByRole("button", { name: "Call Tool", exact: true }).click();
  const frame = page.frameLocator("iframe").frameLocator("iframe");
  await expect(frame.getByRole("main")).toBeVisible();
  await expect.poll(async () => await frame.getByRole("alert").count() > 0 || await frame.locator("h1").textContent() !== "Waiting for household information").toBe(true);
  // Constrain the host's viewport without modifying its renderer or bridge.
  await page.locator("iframe").evaluate(element => { element.style.border = "0"; element.style.width = "768px"; element.style.height = "480px"; });
  return { frame, calls };
}

for (const kind of Object.keys(tools)) for (const theme of ["light", "dark"]) {
  test(`${kind} ${theme} inline`, async ({ page }) => {
    const { frame } = await mount(page, kind, theme);
    await expect(frame.locator(".canvas")).toHaveScreenshot(`${kind}-${theme}-inline.png`);
    expect(await frame.locator(".rows li").count()).toBeLessThanOrEqual(3);
    expect(await frame.locator("button.primary").count()).toBeLessThanOrEqual(1);
    expect(await frame.locator(".content").evaluate(el => el.scrollHeight <= el.clientHeight)).toBe(true);
  });
}

for (const kind of ["plan", "scorecard"]) for (const theme of ["light", "dark"]) {
  test(`${kind} ${theme} fullscreen`, async ({ page }) => {
    const { frame } = await mount(page, kind, theme);
    await page.setViewportSize({ width: 800, height: 512 });
    await frame.getByRole("button", { name: "Open details" }).click();
    await expect(frame.locator("main")).toHaveClass(/fullscreen/);
    await expect(frame.locator(".canvas")).toHaveScreenshot(`${kind}-${theme}-fullscreen.png`);
  });
}

test("plan binds exact consent and ignores duplicate gestures", async ({ page }) => {
  const { frame, calls } = await mount(page, "plan");
  await frame.getByRole("button", { name: "Approve plan" }).click();
  await expect.poll(() => calls.length).toBe(2);
  expect(calls[1].name).toBe("approve_action");
  expect(calls[1].arguments.plan_id).toBe(fixtures.results.plan.data.plan.plan_id);
  expect(calls[1].arguments.version).toBe(fixtures.results.plan.data.plan.version);
  expect(calls[1].arguments.request_id).toBeTruthy();
});

test("door state changes only on a later observation", async ({ page }) => {
  const initial = fixtures.results.doorbell;
  const returned = structuredClone(initial);
  returned.data.presentation.lock_state = "unlocked";
  const { frame, calls } = await mount(page, "doorbell", "light", request => request.name === "execute_household_action" ? { ...initial, speakable: { headline: "Phone approval is unavailable.", details: [], options: [] }, data: { status: "phone_required" } } : returned);
  await frame.getByRole("button", { name: "Request 10-minute unlock" }).click();
  await expect(frame.getByText("Observed: locked")).toBeVisible();
  await expect(frame.getByText("Phone approval is unavailable.")).toBeVisible();
  await advance(page, 2200);
  await expect(frame.getByText("Observed: unlocked")).toBeVisible();
  expect(calls.filter(c => c.name === "execute_household_action")).toHaveLength(1);
});

test("keyboard controls and reduced motion", async ({ page }) => {
  const { frame } = await mount(page, "plan");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await frame.getByRole("button", { name: "Approve plan" }).focus();
  await expect(frame.getByRole("button", { name: "Approve plan" })).toBeFocused();
  expect(await frame.locator(".ev-bar span").evaluate(el => getComputedStyle(el).transitionDuration)).toBe("0s");
  for (const button of await frame.getByRole("button").all()) expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(48);
});

test("1280 by 800 scaling", async ({ page }) => {
  const { frame } = await mount(page, "plan");
  await page.setViewportSize({ width: 1500, height: 1100 });
  await page.locator("iframe").evaluate(el => { el.style.width = "1280px"; el.style.height = "800px"; });
  await expect.poll(async () => Math.round((await frame.locator("main").boundingBox())!.width)).toBe(1280);
});

for (const approved of [true, false]) test(`action response ${approved}`, async ({ page }) => {
  const { frame, calls } = await mount(page, "approval", "light", () => ({ speakable: { headline: "Your response was recorded.", details: [], options: [] }, data: { status: "recorded" } }));
  await frame.getByRole("button", { name: approved ? "Approve" : "Deny", exact: true }).click();
  await expect.poll(() => calls.length).toBe(2);
  expect(calls[1].arguments.approved).toBe(approved);
  expect(calls[1].arguments.approval_id).toBe(fixtures.results.approval.data.decision.approval.approval_id);
  await expect(frame.getByRole("heading", { name: "Your response was recorded." })).toBeVisible();
});

test("security never offers card approval", async ({ page }) => {
  const initial = structuredClone(fixtures.results.approval);
  initial.data.presentation.phone_required = true;
  initial.data.presentation.can_respond = true; // Even inconsistent input cannot bypass the phone requirement.
  const { frame } = await mount(page, "approval", "light", undefined, initial);
  await expect(frame.getByText(/Phone approval is unavailable/)).toBeVisible();
  await expect(frame.getByRole("button", { name: "Approve", exact: true })).toHaveCount(0);
});

test("retry retains the exact gesture key", async ({ page }) => {
  let attempts = 0;
  const { frame, calls } = await mount(page, "plan", "light", () => ++attempts === 1 ? new Error("Expired authentication") : { speakable: { headline: "The displayed plan has changed.", details: [], options: [] }, data: { status: "denied" } });
  await frame.getByRole("button", { name: "Approve plan" }).click();
  await expect(frame.getByRole("button", { name: "Approve plan" })).toBeDisabled();
  await frame.getByRole("button", { name: "Retry", exact: true }).click();
  await expect.poll(() => calls.length).toBe(3);
  expect(calls[1].arguments).toEqual(calls[2].arguments);
  await expect(frame.getByRole("heading", { name: "The displayed plan has changed." })).toBeVisible();
  await expect(frame.getByRole("button", { name: "Approve plan" })).toHaveCount(0);
});

test("numeric car limit records a revision then polls", async ({ page }) => {
  const preparing = { speakable: { headline: "Your limit is recorded. The plan is updating.", details: [], options: [] }, data: { status: "preparing" } };
  const { frame, calls } = await mount(page, "plan", "light", request => request.name === "revise_household_plan" ? preparing : fixtures.results.plan);
  await frame.getByRole("button", { name: "Open details" }).click();
  await frame.getByLabel("Car charge limit (%)").fill("50");
  await frame.getByRole("button", { name: "Update limit" }).click();
  await expect.poll(() => calls.length).toBe(2);
  expect(calls[1].arguments.percent).toBe(50);
  expect(calls[1].arguments.change).toBe("car_limit");
  await advance(page, 1100);
  await expect.poll(() => calls.length).toBeGreaterThanOrEqual(3);
  expect(calls[2].name).toBe("get_household_plan");
});

function pending() {
  const initial = structuredClone(fixtures.results.verification);
  const expires = new Date(Date.parse(fixtures.at) + 120000).toISOString();
  initial.data.presentation.status = "pending";
  initial.data.presentation.can_check = false;
  initial.data.presentation.valid_until = expires;
  initial.data.case.verification = { status: "pending", sent_to: initial.data.case.subject.contact_id, started_at: fixtures.at, expires_at: expires };
  return initial;
}

for (const status of ["genuine", "not_genuine", "will_call", "no_answer"]) test(`verification ${status} stops polling`, async ({ page }) => {
  const initial = pending();
  const terminal = structuredClone(initial);
  terminal.data.presentation.status = status;
  terminal.data.case.verification.status = status;
  terminal.speakable.headline = status === "genuine" ? "Talk to the contact using their saved number." : "Contact the person through a channel you trust.";
  const { frame, calls } = await mount(page, "verification", "light", () => terminal, initial);
  await advance(page, 2100);
  await expect(frame.getByRole("status")).toHaveText(status.replaceAll("_", " "));
  const stopped = calls.length;
  await advance(page, 5000);
  expect(calls.length).toBe(stopped);
  await expect(frame.getByText(/send money|pay now/i)).toHaveCount(0);
});

test("pending expiry does not invent a reply", async ({ page }) => {
  const initial = pending();
  const { frame, calls } = await mount(page, "verification", "light", () => initial, initial);
  await page.clock.setFixedTime(new Date(Date.parse(fixtures.at) + 121000));
  await expect(frame.getByRole("status")).toHaveText("pending");
  await expect(frame.getByRole("button", { name: "Refresh", exact: true })).toBeVisible();
  const stopped = calls.length;
  await advance(page, 5000);
  expect(calls.length).toBe(stopped);
});

test("malformed results have no action controls", async ({ page }) => {
  const initial = structuredClone(fixtures.results.plan);
  initial.data.presentation.kind = "unknown";
  const { frame } = await mount(page, "plan", "light", undefined, initial);
  await expect(frame.getByRole("alert")).toBeVisible();
  await expect(frame.locator("button.primary")).toHaveCount(0);
});

test("card makes no direct network requests", async ({ page }) => {
  const direct: string[] = [];
  page.on("request", request => { if (request.frame().parentFrame()?.parentFrame()) direct.push(request.url()); });
  const { frame } = await mount(page, "plan");
  await frame.getByRole("button", { name: "Approve plan" }).click();
  expect(direct).toEqual([]);
});

async function notify(page: Page, method: string, params: unknown) {
  await page.frameLocator("iframe").locator("iframe").evaluate((element, message) => {
    (element as HTMLIFrameElement).contentWindow!.postMessage(message, "*");
  }, { jsonrpc: "2.0", method, params });
}

test("unsupported fullscreen is not offered", async ({ page }) => {
  const { frame } = await mount(page, "plan");
  await notify(page, "ui/notifications/host-context-changed", { availableDisplayModes: ["inline"] });
  await expect(frame.getByRole("button", { name: "Open details" })).toHaveCount(0);
});

test("preparation polling stops at thirty seconds with manual refresh", async ({ page }) => {
  const preparing = { speakable: { headline: "Preparing your plan.", details: [], options: [] }, data: { status: "preparing" } };
  const { frame, calls } = await mount(page, "plan", "light", () => preparing, preparing);
  await advance(page, 1100);
  await expect.poll(() => calls.length).toBe(2);
  await page.clock.setFixedTime(new Date(Date.parse(fixtures.at) + 31000));
  await expect(frame.getByRole("button", { name: "Refresh", exact: true })).toBeVisible();
  const stopped = calls.length;
  await advance(page, 3000);
  expect(calls.length).toBe(stopped);
});

test("one outstanding poll pauses while hidden and stops on error", async ({ page }) => {
  let finish!: (value: unknown) => void;
  const response = new Promise(resolve => { finish = resolve; });
  const { frame, calls } = await mount(page, "doorbell", "light", () => response);
  await frame.locator("main").evaluate(() => Object.defineProperty(document, "hidden", { configurable: true, value: true }));
  await advance(page, 5000);
  expect(calls.length).toBe(1);
  await frame.locator("main").evaluate(() => Object.defineProperty(document, "hidden", { configurable: true, value: false }));
  await advance(page, 2100);
  await expect.poll(() => calls.length).toBe(2);
  await advance(page, 6000);
  expect(calls.length).toBe(2);
  finish(new Error("Unavailable"));
  await expect(frame.getByRole("alert")).toBeVisible();
  await advance(page, 6000);
  expect(calls.length).toBe(2);
});

test("replaced content rejects a late gesture reply and duplicate clicks", async ({ page }) => {
  let finish!: (value: unknown) => void;
  const response = new Promise(resolve => { finish = resolve; });
  const { frame, calls } = await mount(page, "plan", "light", () => response);
  await frame.getByRole("button", { name: "Approve plan" }).dblclick();
  await expect.poll(() => calls.length).toBe(2);
  const replacement = { speakable: { headline: "This plan was replaced.", details: [], options: [] }, data: { status: "unavailable" } };
  await notify(page, "ui/notifications/tool-result", { content: [], structuredContent: replacement });
  await expect(frame.getByRole("heading", { name: replacement.speakable.headline })).toBeVisible();
  finish(fixtures.results.plan);
  await expect(frame.getByRole("main")).toHaveAttribute("aria-busy", "false");
  await expect(frame.getByRole("heading", { name: replacement.speakable.headline })).toBeVisible();
  expect(calls.length).toBe(2);
});

for (const theme of ["light", "dark"]) test(`${theme} text and button contrast`, async ({ page }) => {
  const { frame } = await mount(page, "plan", theme);
  function luminance(rgb: string) {
    const channels = rgb.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(c => c / 255).map(c => c <= .04045 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4);
    return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;
  }
  for (const selector of ["body", "button.primary", ".rows li"]) {
    const [foreground, background] = await frame.locator(selector).first().evaluate(el => [getComputedStyle(el).color, getComputedStyle(el).backgroundColor]);
    const values = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
    expect((values[0] + .05) / (values[1] + .05)).toBeGreaterThanOrEqual(4.5);
  }
});

test("unknown observed lock state disables unlock even with contradictory eligibility", async ({ page }) => {
  const initial = structuredClone(fixtures.results.doorbell);
  initial.data.presentation.lock_state = "unknown";
  const { frame } = await mount(page, "doorbell", "light", () => initial, initial);
  await expect(frame.getByText("Lock state unavailable")).toBeVisible();
  await expect(frame.getByRole("button", { name: "Request 10-minute unlock" })).toHaveCount(0);
});

test("scorecard pagination preserves the selected query", async ({ page }) => {
  const initial = structuredClone(fixtures.results.scorecard);
  initial.data.cursor = "opaque-next-page";
  const { frame, calls } = await mount(page, "scorecard", "light", () => fixtures.results.scorecard, initial);
  await frame.getByRole("button", { name: "Open details" }).click();
  await frame.getByRole("button", { name: "Next page" }).click();
  await expect.poll(() => calls.length).toBe(2);
  expect(calls[1].arguments).toEqual({ ...(fixtures.inputs?.scorecard ?? {}), cursor: "opaque-next-page" });
});
